on:
  pull_request:
    branches: [dev, master]
name: Security

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/cache@v2
      id: cache-db
      with:
        path: ~/.symfony/cache
        key: db

    - name: Run dependencies security checker
      id: dependencies
      working-directory: ./
      run: |
        docker run --rm -v $(pwd):$(pwd) -w $(pwd) symfonycorp/cli check:security 2>&1 | tee security.report
        message=$(awk '/Symfony Security Check Report/, 0' security.report)
        message="${message//$'\n'/<br />}"
        echo "::set-output name=message::$message"

    - name: Report dependencies security vulnerabilities
      if: always()
      uses: phulsechinmay/rewritable-pr-comment@v0.2.1
      with:
        message: '<h2>:closed_lock_with_key: Dependencies security vulnerabilities</h2><pre>${{ steps.dependencies.outputs.message }}</pre>'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMENT_IDENTIFIER: 'php-security-checker-action'